### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by rmiller335** [humhub-contrib/devtools#23]
I couldn't get this to work via the web (no errors but no module created), so I'm trying at the console.  I've had to modify the suggested console.php to this:

```
return [
	'bootstrap' => ['gii'],
	'modules' => [
		'gii' => [
			'class' => 'yii\gii\Module',
			'allowedIPs' => ['127.0.0.1', '::1'],

			'generators' => [
				'module' => [
					'class' => 'humhub\modules\devtools\gii\generators\ModuleGenerator',
					'templates' => [
						'humhub' => '@app/humhub/modules/devtools/gii/templates/modules/simple'
					]
				]
			],
		],
	],
];
```
... which seems to find the class and the template, but then I get this error:

```
rmiller@rc-prod:~/dev/humhub/protected$ php yii gii/module --moduleClass='app\modules\teal\Onboarding' --moduleID=tealonboarding --template=humhub
Running 'HumHub Module Generator'...

Exception 'Error' with message 'Call to a member function getNameSpace() on string'

in /home/rmiller/dev/humhub/protected/humhub/modules/devtools/gii/templates/modules/simple/config.php:9

Stack trace:
#0 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require()
#1 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#2 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2-gii/src/Generator.php(317): yii\base\View->renderFile()
#3 /home/rmiller/dev/humhub/protected/humhub/modules/devtools/gii/generators/ModuleGenerator.php(187): yii\gii\Generator->render()
#4 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(53): humhub\modules\devtools\gii\generators\ModuleGenerator->generate()
#5 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2-gii/src/console/GenerateAction.php(36): yii\gii\console\GenerateAction->generateCode()
#6 [internal function]: yii\gii\console\GenerateAction->run()
#7 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array()
#8 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Action->runWithParams()
#9 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction()
#10 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction()
#11 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction()
#12 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction()
#13 /home/rmiller/dev/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest()
#14 /home/rmiller/dev/humhub/protected/yii(29): yii\base\Application->run()
#15 {main}
```
Can anybody tell me what I'm missing?

Thanks,
Bob

**Comment by alnickle** [comment]
Similar experience for me with the changes from ^^; I had to remove the "humhub" part of the template path to even get this far.
